const entries = {
  sail: ["Sail", "Naviguer"],
  fish: ["Fish", "Pêcher"],
  fishStock: ["Fish in hold", "Poissons en cale"],
  sell: ["Sell fish", "Vendre"],
  explore: ["Explore", "Explorer"],
  build: ["Build", "Construire"],
  buy: ["Export", "Exporter"],
  draw: ["Draw", "Dessiner"],
  tourist: ["Tourists", "Touristes"],
  rest: ["Rest", "Se reposer"],
  round: ["Round", "Tour"],
  character: ["Choose a character", "Choisir un personnage"],
  plan: ["Plan your actions", "Programmer les actions"],
  actions: ["Choose an action", "Choisir une action"],
  expand: ["Extend the archipelago", "Agrandir l’archipel"],
  neutral: ["Place the neutral markers", "Placer les pions neutres"],
  ended: ["Final scores", "Scores finaux"],
  confirm: ["Confirm", "Confirmer"],
  choose: ["Choose", "Choisir"],
  cancel: ["Cancel", "Annuler"],
  undo: ["Undo", "Annuler"],
  waiting: ["Waiting for", "Au tour de"],
  you: ["You", "Vous"],
  spectator: ["Spectator", "Spectateur"],
  journal: ["Journal", "Journal"],
  chat: ["Chat", "Discussion"],
  help: ["Rules & help", "Règles et aide"],
  first: ["First player", "Premier joueur"],
  both: ["Vatu + prosperity", "Vatu + prospérité"],
  point: ["Prosperity", "Prospérité"],
  coin: ["Vatu", "Vatu"],
  kava: ["Kava", "Kava"],
  copra: ["Copra", "Coprah"],
  beef: ["Beef", "Bœuf"],
  water: ["Rising Waters", "La Montée des eaux"],
  ability: ["Use character", "Utiliser le personnage"],
  treasure: ["Sell treasures", "Vendre des trésors"],
  beg: ["Exchange prosperity", "Échanger de la prospérité"],
  governor: ["Move markers", "Déplacer les pions"],
  discard: ["Retrieve markers", "Reprendre les pions"],
  restChoice: ["Choose a rest token", "Choisir un jeton Repos"],
  bonus: ["Character bonus", "Bonus du personnage"],
  cost: ["Cost", "Coût"],
  income: ["Income", "Revenus"],
  gain: ["Gain", "Gain"],
  island: ["Island", "Île"],
  sea: ["Ocean", "Océan"],
  hut: ["Hut", "Cabane"],
  dike: ["Dike", "Digue"],
  market: ["Fish price", "Prix du poisson"],
  demand: ["Foreign trade", "Commerce extérieur"],
  next: ["Next islands", "Prochaines tuiles"],
  stock: ["Available", "Disponible"],
  board: ["Back to board", "Retour au plateau"],
  full: ["Full screen", "Plein écran"],
  fit: ["Fit board", "Ajuster le plateau"],
  zoom: ["Zoom board", "Agrandir le plateau"],
  colorBlind: ["Color-blind mode", "Mode daltonien"],
  sound: ["Game sounds", "Sons du jeu"],
  credit: ["Credits", "Crédits"],
  rules: ["Simplified rules", "Règles simplifiées"],
  original: ["Original rulebook", "Règles originales"],
  twoPlayer: ["Two-player rules", "Règles à deux joueurs"],
  source: ["Source code", "Code source"],
  noMoves: ["No action available", "Aucune action disponible"],
  waterLeft: [
    "Actions until the waters rise",
    "Actions avant la montée des eaux",
  ],
  finished: ["Game finished", "Partie terminée"],
  lost: ["The islands were submerged", "Les îles ont été submergées"],
  won: ["Winner", "Vainqueur"],
  markers: ["Markers", "Pions"],
  skip: [
    "No legal effect: retrieve markers",
    "Action impossible : reprendre les pions",
  ],
  demo: ["Local practice", "Entraînement local"],
  newGame: ["New game", "Nouvelle partie"],
  bots: ["Play with bots", "Jouer avec des bots"],
  hotseat: ["Control every seat", "Contrôler tous les joueurs"],
  step: ["Bot move", "Coup automatique"],
  auto: ["Autoplay", "Jeu automatique"],
  saved: ["Saved locally", "Sauvegardé localement"],
  selected: ["Selected", "Sélectionné"],
  pending: ["Sending…", "Envoi…"],
  connected: ["Waiting for the game…", "Chargement de la partie…"],
  replay: ["Replay", "Replay"],
  wealth: ["Wealth", "Richesse"],
  touristScore: ["Visitors × huts", "Touristes × cabanes"],
  preferences: ["Preferences", "Préférences"],
};
export function translator(lang) {
  return (key) => entries[key]?.[0] ?? key;
}
export const characterHelp = {
  navigator: [
    "Sail 1–3 spaces for free.",
    "Naviguer de 1 à 3 cases gratuitement.",
  ],
  fisherman: [
    "Fishing also earns prosperity equal to the fish tile.",
    "La pêche rapporte aussi autant de prospérité que la tuile Poisson.",
  ],
  vendor: [
    "Sell fish without being beside one of your huts.",
    "Vendre du poisson sans être près d’une de vos cabanes.",
  ],
  diver: [
    "Diving also earns vatus equal to the treasure tile.",
    "Explorer rapporte aussi autant de vatus que la tuile Trésor.",
  ],
  builder: [
    "A hut costs 1 vatu instead of 3.",
    "Une cabane coûte 1 vatu au lieu de 3.",
  ],
  buyer: [
    "Export a second matching good from the reserve for free.",
    "Exporter gratuitement un second cube identique de la réserve.",
  ],
  artist: [
    "A drawing earns 5 prosperity instead of 3.",
    "Un dessin rapporte 5 prospérité au lieu de 3.",
  ],
  guide: [
    "Transporting a tourist earns 2 prosperity per drawing on that island.",
    "Transporter un touriste rapporte 2 prospérité par dessin sur cette île.",
  ],
  beggar: [
    "Once per round, exchange up to 3 prosperity for the same number of vatus.",
    "Une fois par tour, échanger jusqu’à 3 prospérité contre autant de vatus.",
  ],
  preacher: [
    "If you hold no majority, perform one planned action anyway.",
    "Sans aucune majorité, effectuer tout de même une action programmée.",
  ],
  governor: [
    "Instead of an action, move your entire stack to another action.",
    "Au lieu d’une action, déplacer toute une pile vers une autre action.",
  ],
};
